// <auto-generated />
using Mafaka.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mafaka.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221209104745_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mafaka.Services.ProductAPI.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Game",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur accumsan sem in lorem convallis ultricies. Curabitur vulputate accumsan lectus condimentum elementum. Phasellus tincidunt, velit in maximus consequat, sem enim ullamcorper velit, in sollicitudin dui nisl non ex. Maecenas sed libero porta erat accumsan tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus quis tellus odio. Fusce pharetra ipsum vitae diam tempus posuere. In gravida tincidunt velit, eu porttitor risus commodo a. Suspendisse potenti. Etiam ac euismod eros. Nam aliquet augue a velit luctus, a euismod arcu mollis. Proin quis nisl tincidunt, vehicula dui in, ultrices velit.",
                            ImageUrl = "https://mafakastorage.blob.core.windows.net/mafakablob/img/57e9d5434c54af14f1dc8460962e33791c3ad6e04e507440752f78d79e45c5_640.jpg",
                            Name = "Dota 2",
                            Price = 1488.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Game",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur accumsan sem in lorem convallis ultricies. Curabitur vulputate accumsan lectus condimentum elementum. Phasellus tincidunt, velit in maximus consequat, sem enim ullamcorper velit, in sollicitudin dui nisl non ex. Maecenas sed libero porta erat accumsan tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus quis tellus odio. Fusce pharetra ipsum vitae diam tempus posuere. In gravida tincidunt velit, eu porttitor risus commodo a. Suspendisse potenti. Etiam ac euismod eros. Nam aliquet augue a velit luctus, a euismod arcu mollis. Proin quis nisl tincidunt, vehicula dui in, ultrices velit.",
                            ImageUrl = "https://mafakastorage.blob.core.windows.net/mafakablob/img/55e6d04a4f56a414f1dc8460962e33791c3ad6e04e507440722d72d19548c1_640.jpg",
                            Name = "LoL",
                            Price = 8.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Game",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur accumsan sem in lorem convallis ultricies. Curabitur vulputate accumsan lectus condimentum elementum. Phasellus tincidunt, velit in maximus consequat, sem enim ullamcorper velit, in sollicitudin dui nisl non ex. Maecenas sed libero porta erat accumsan tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus quis tellus odio. Fusce pharetra ipsum vitae diam tempus posuere. In gravida tincidunt velit, eu porttitor risus commodo a. Suspendisse potenti. Etiam ac euismod eros. Nam aliquet augue a velit luctus, a euismod arcu mollis. Proin quis nisl tincidunt, vehicula dui in, ultrices velit.",
                            ImageUrl = "https://mafakastorage.blob.core.windows.net/mafakablob/img/54e0d6404850ab14f1dc8460962e33791c3ad6e04e5074417c2d78d39644c5_640.jpg",
                            Name = "Sea of Thieves",
                            Price = 999.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Game",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur accumsan sem in lorem convallis ultricies. Curabitur vulputate accumsan lectus condimentum elementum. Phasellus tincidunt, velit in maximus consequat, sem enim ullamcorper velit, in sollicitudin dui nisl non ex. Maecenas sed libero porta erat accumsan tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus quis tellus odio. Fusce pharetra ipsum vitae diam tempus posuere. In gravida tincidunt velit, eu porttitor risus commodo a. Suspendisse potenti. Etiam ac euismod eros. Nam aliquet augue a velit luctus, a euismod arcu mollis. Proin quis nisl tincidunt, vehicula dui in, ultrices velit.",
                            ImageUrl = "https://mafakastorage.blob.core.windows.net/mafakablob/img/54e0d14a4e57b10ff3d8992cc12c30771037dbf85254784e77267ed69249_640.jpg",
                            Name = "Rust",
                            Price = 1.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
